### ISSUE TITLE
LD2410 config?

### ISSUE THREAD

**Issue by mochoandre** [patrick3399/Hi-Link_mmWave_Radar_ESPHome#10]
Is it possible to have access to LD2410 Config?

**Comment by patrick3399** [comment]
In development

**Comment by Electronlibre2012** [comment]
Thanks @patrick3399 for your awesome work!

i use a LD1115H and it works like a charm!

LD2410H are a lot cheaper, so i hope you will succeed in the dev part ;)

is it in on a good way or you think it will be complicated to achieve the dev part please?

**Comment by markmghali** [comment]
I am also curious about this! I have both ld1115h and ld2410-C. I know ld2410 is now officially part of esphome. Still curious what you come up with patrick.

Thank you again for your amazing work

**Comment by patrick3399** [comment]
> I am also curious about this! I have both ld1115h and ld2410-C. I know ld2410 is now officially part of esphome. Still curious what you come up with patrick.
> 
> Thank you again for your amazing work

Official Support is good. I will give some suggestion on official LD2410 branch.

**Comment by patrick3399** [comment]
ESPHome Offical support already.
And Home Assistant Direct Bluetooth integration available.
