### ISSUE TITLE
LD1125H - I need more info

### ISSUE THREAD

**Issue by AnatolSher** [patrick3399/Hi-Link_mmWave_Radar_ESPHome#11]
Hi
Is it possible to find datasheet for MMIC chip and schematic diagram for ld1125 module?
I want to test a couple of ideas :)

**Comment by patrick3399** [comment]
No datasheet i have ,maybe you should contect the company for these infomation.

**Comment by AnatolSher** [comment]
Thanks Patric. I will try

**Comment by AnatolSher** [comment]
MMIC chip is SRK1101A http://sgrsemi.com/

**Comment by patrick3399** [comment]
Solve.
