### ISSUE TITLE
Reduce Polling Interval

### ISSUE THREAD

**Issue by JSmid6** [patrick3399/Hi-Link_mmWave_Radar_ESPHome#22]
Hi, I got my ESP32 working with the LD1125H mmWave sensor but I've noticed it's constantly updating the distance parameter. Is there any way to reduce the frequency this is updated? My homeassistant instance struggles to keep up at times. 

Kind regards,
Johan

**Comment by patrick3399** [comment]
Maybe change the clearance interval?
Or using the sensor fliter, it can slow down the data update interval.

**Comment by JSmid6** [comment]
Changed the heartbeat and the sliding window frequency and that seems to work well
