### ISSUE TITLE
Compiling failed

### ISSUE THREAD

**Issue by davidjac** [patrick3399/Hi-Link_mmWave_Radar_ESPHome#24]
I followed the Yaml for the LD1125 - But get the following when uploading. Any ideas?

INFO ESPHome 2023.8.3
INFO Reading configuration /config/esphome/esp32radar.yaml...
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Core config or version changed, cleaning build files...
INFO Deleting /data/esp32radar/.pioenvs
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.0.9
INFO Compiling app...
Processing esp32radar (board: nodemcu-32s; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50100.0 (5.1.0) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.30.2") 
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-g++
-- Check for working CXX compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
Processing 1 dependencies:
[1/1] idf (5.1.0)
-- Project sdkconfig file /config/esphome/.esphome/build/esp32radar/sdkconfig.esp32radar
-- Configuring incomplete, errors occurred!
See also "/data/esp32radar/.pioenvs/esp32radar/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/root/.platformio/penv/.espidf-5.1.0/bin/python: No module named kconfgen
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/kconfig.cmake:176 (message):
  Failed to run kconfgen
  (/root/.platformio/penv/.espidf-5.1.0/bin/python;-m;kconfgen;--list-separator=semicolon;--kconfig;/data/cache/platformio/packages/framework-espidf/Kconfig;--sdkconfig-rename;/data/cache/platformio/packages/framework-espidf/sdkconfig.rename;--config;/config/esphome/.esphome/build/esp32radar/sdkconfig.esp32radar;--env-file;/data/esp32radar/.pioenvs/esp32radar/config.env).
  Error 1
Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:611 (__kconfig_generate_config)
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:464 (idf_build_process)
  CMakeLists.txt:3 (project)

========================== [FAILED] Took 3.42 seconds ==========================

**Comment by patrick3399** [comment]
Change the ESP-IDF version to recommand, it can solove the problem.
