### ISSUE TITLE
I could not get it to work on an D1-mini, I think either UART is to slow or the whole chip has to little processing power. Same configuration works flawless with an esp32

### ISSUE THREAD

**Issue by qkddn49** [patrick3399/Hi-Link_mmWave_Radar_ESPHome#3]

**Comment by nickelnine** [comment]
May I ask which ESP32 board specifically you use? And did you flash the Normal or Complete yaml?

**Comment by patrick3399** [comment]
Normal is some parts of complete yaml.
If you want to customized your device, normal is your choice.
These code are test on Nodemcu 32s and Devkit typeB, on ESPhome 2022.08 version.
