### ISSUE TITLE
LD1115H with Wemos D1 mini consume 3-4% of CPU Intel NUC8 I5

### ISSUE THREAD

**Issue by Electronlibre2012** [patrick3399/Hi-Link_mmWave_Radar_ESPHome#5]
Hello,

great work! works like a charm BUT...the sensor consume between 3 and 4% of my CPU...that's a lot of "power"...because my NUC is a NUC8 with a quad core I5 2.3Ghz to 3.6Ghz...

Is it normal for you?

Can't imagine have 10 sensor like this one...will consume 30-40% of my CPU...not reliable...

Thanks

**Comment by patrick3399** [comment]
Try to exclude all the entity in Logger, but include the Occupancy binary sensor.
